/**
 * QCET E-Office: RFC 9457 Problem Details for HTTP APIs
 *
 * Implements IETF RFC 9457 (superseding RFC 7807) Problem Details standard
 * as accepted in ADR-007.
 *
 * Media Type: application/problem+json
 * Specification: https://datatracker.ietf.org/doc/html/rfc9457
 */

import { NextResponse } from 'next/server';
import { ZodError } from 'zod';
import { ApiError, toApiErrorResponse } from './errors';

export const PROBLEM_DETAILS_CONTENT_TYPE = 'application/problem+json';
export const DEFAULT_ERROR_URI_BASE = 'https://qcet.edu.vn/errors';

/**
 * RFC 9457 Invalid Parameter Item
 */
export interface ProblemInvalidParam {
  name: string;
  reason: string;
}

/**
 * Standard RFC 9457 Problem Details structure
 */
export interface ProblemDetails {
  /**
   * URI reference that identifies the problem type
   */
  type: string;
  /**
   * Short, human-readable summary of the problem type
   */
  title: string;
  /**
   * HTTP status code generated by the origin server for this occurrence
   */
  status: number;
  /**
   * Human-readable explanation specific to this occurrence of the problem
   */
  detail: string;
  /**
   * URI reference that identifies the specific occurrence of the problem
   */
  instance?: string;
  /**
   * Machine-readable error code specific to QCET E-Office
   */
  code?: string;
  /**
   * Request tracking identifier for observability and audit
   */
  requestId?: string;
  /**
   * Validation parameter violations (RFC 9457 extension)
   */
  invalidParams?: ProblemInvalidParam[];
  /**
   * Extension members
   */
  [key: string]: unknown;
}

/**
 * Standard title mappings by HTTP status code
 */
const STATUS_TITLES: Record<number, string> = {
  400: 'Bad Request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not Found',
  409: 'Conflict',
  412: 'Precondition Failed',
  413: 'Payload Too Large',
  415: 'Unsupported Media Type',
  422: 'Unprocessable Content',
  429: 'Too Many Requests',
  500: 'Internal Server Error',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
};

/**
 * Converts error codes into kebab-case slugs for type URIs
 */
function codeToSlug(code: string): string {
  return code
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export interface ToProblemDetailsOptions {
  requestId?: string;
  instance?: string;
  typeBaseUri?: string;
  detail?: string;
  title?: string;
  type?: string;
}

/**
 * Transforms any error or exception into a standard RFC 9457 Problem Details object
 */
export function toProblemDetails(
  error: unknown,
  options: ToProblemDetailsOptions = {}
): { status: number; problem: ProblemDetails } {
  const requestId = options.requestId || 'req_unknown';
  const baseUri = options.typeBaseUri || DEFAULT_ERROR_URI_BASE;

  // Use canonical toApiErrorResponse to resolve baseline status, code, and message
  const { status, body } = toApiErrorResponse(error, requestId);

  const code = body.code || 'INTERNAL_ERROR';
  const defaultTitle = STATUS_TITLES[status] || 'Error';
  const title = options.title || defaultTitle;
  const detail = options.detail || body.message || defaultTitle;

  const type =
    options.type ||
    (code !== 'INTERNAL_ERROR'
      ? `${baseUri}/${codeToSlug(code)}`
      : 'about:blank');

  const problem: ProblemDetails = {
    type,
    title,
    status,
    detail,
    code,
    requestId,
  };

  if (options.instance) {
    problem.instance = options.instance;
  }

  // Extract invalidParams from fieldErrors or ZodError
  if (body.fieldErrors && Object.keys(body.fieldErrors).length > 0) {
    const invalidParams: ProblemInvalidParam[] = [];
    for (const [name, reasons] of Object.entries(body.fieldErrors)) {
      for (const reason of reasons) {
        invalidParams.push({ name, reason });
      }
    }
    problem.invalidParams = invalidParams;
  } else if (error instanceof ZodError) {
    const invalidParams: ProblemInvalidParam[] = error.issues.map((issue) => ({
      name: issue.path.length > 0 ? issue.path.join('.') : '_root',
      reason: issue.message,
    }));
    problem.invalidParams = invalidParams;
  }

  return { status, problem };
}

export interface ProblemResponseOptions extends ToProblemDetailsOptions {
  headers?: HeadersInit;
}

/**
 * Creates a NextResponse with Content-Type: application/problem+json adhering to RFC 9457
 */
export function problemResponse(
  error: unknown,
  options: ProblemResponseOptions = {}
): NextResponse<ProblemDetails> {
  const { status, problem } = toProblemDetails(error, options);

  const headers = new Headers(options.headers);
  headers.set('Content-Type', PROBLEM_DETAILS_CONTENT_TYPE);
  if (problem.requestId && !headers.has('x-request-id')) {
    headers.set('x-request-id', problem.requestId);
  }

  return NextResponse.json(problem, {
    status,
    headers,
  });
}
